version: "3.7"
services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 9009 --reload
    ports:
      - "9009:9009"
    environment:
      - SQLITE_PATH=/sql_app.db
    volumes:
      - .:/code
      - "./data/sqlite.db:/sql_app.db"
